{
 "title": "Job",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "g_cluster_name", "label": "Cluster", "query": { "query": "label_values(cluster_name)" } },
   {
    "name": "g_job_id",
    "label": "Job",
    "query": {
     "query": "label_values({cluster_name=\"$g_cluster_name\"},job_id)"
    }
   },
   {
    "name": "g_pod",
    "label": "Pod",
    "query": {
     "query": "label_values({cluster_name=\"$g_cluster_name\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Name",
   "type": "text",
   "description": "Name of the job ID or pod",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "content": "${g_job_id}\n${g_pod}" }
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "description": "% of VRAM used across all GPUs this job or pod is running on",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/$B", "type": "math" },
    { "expression": "$C/$D", "type": "math" }
   ]
  },
  {
   "title": "PCIe Max Speed",
   "type": "stat",
   "description": "Maximum PCIe speed",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pcie_max_speed{job_id!=\"\", job_id=\"$g_job_id\"})",
     "legendFormat": "{{job_id}}"
    },
    {
     "expr": "max(pcie_max_speed{pod!=\"\", pod=\"$g_pod\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PCIe Counts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(pcie_recovery_count{job_id!=\"\", job_id=\"$g_job_id\"}[$__interval]))",
     "legendFormat": "Recovery"
    },
    {
     "expr": "sum(delta(pcie_recovery_count{pod!=\"\", pod=\"$g_pod\"}[$__interval]))",
     "legendFormat": "Recovery"
    },
    {
     "expr": "sum(delta(pcie_replay_count{job_id!=\"\", job_id=\"$g_job_id\"}[$__interval]))",
     "legendFormat": "Replay"
    },
    {
     "expr": "sum(delta(pcie_replay_count{pod!=\"\", pod=\"$g_pod\"}[$__interval]))",
     "legendFormat": "Replay"
    },
    {
     "expr": "sum(delta(pcie_replay_rollover_count{job_id!=\"\", job_id=\"$g_job_id\"}[$__interval]))",
     "legendFormat": "Replay Rollover"
    },
    {
     "expr": "sum(delta(pcie_replay_rollover_count{pod!=\"\", pod=\"$g_pod\"}[$__interval]))",
     "legendFormat": "Replay Rollover"
    },
    {
     "expr": "sum(delta(pcie_nack_received_count{job_id!=\"\", job_id=\"$g_job_id\"}[$__interval]))",
     "legendFormat": "NACK Received"
    },
    {
     "expr": "sum(delta(pcie_nack_received_count{pod!=\"\", pod=\"$g_pod\"}[$__interval]))",
     "legendFormat": "NACK Received"
    },
    {
     "expr": "sum(delta(pcie_nack_sent_count{job_id!=\"\", job_id=\"$g_job_id\"}[$__interval]))",
     "legendFormat": "NACK Sent"
    },
    {
     "expr": "sum(delta(pcie_nack_sent_count{pod!=\"\", pod=\"$g_pod\"}[$__interval]))",
     "legendFormat": "NACK Sent"
    }
   ]
  },
  {
   "title": "Top 5 GPU Usage",
   "type": "stat",
   "description": "Top 5 current GPU GFX Activity, labeled with hostname and GPU ID.",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(5, gpu_gfx_activity{job_id!=\"\", job_id=\"$g_job_id\"})",
     "legendFormat": "{{hostname}} | {{gpu_id}}"
    },
    {
     "expr": "topk(5, gpu_gfx_activity{pod!=\"\", pod=\"$g_pod\"})",
     "legendFormat": "{{hostname}} | {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Top 5 Used VRAM",
   "type": "stat",
   "description": "Top 5 GPUs with highest VRAM used, labeled with hostname and GPU ID.",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "topk(5, gpu_used_vram{job_id!=\"\", job_id=\"$g_job_id\"})",
     "legendFormat": "{{hostname}} | {{gpu_id}}"
    },
    {
     "expr": "topk(5, gpu_used_vram{pod!=\"\", pod=\"$g_pod\"})",
     "legendFormat": "{{hostname}} | {{gpu_id}}"
    }
   ]
  },
  {
   "title": "Total Current PCIe Bandwidth",
   "type": "stat",
   "description": "Total current PCIe bandwidth",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pcie_bandwidth{job_id!=\"\", job_id=\"$g_job_id\"})",
     "legendFormat": "PCIe Bandwidth"
    },
    {
     "expr": "sum(pcie_bandwidth{pod!=\"\", pod=\"$g_pod\"})",
     "legendFormat": "PCIe Bandwidth"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Compute Nodes",
   "type": "stat",
   "description": "\\# of compute nodes used by the job",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by(hostname) (gpu_gfx_activity{job_id!=\"\", job_id=\"$g_job_id\"}))",
     "legendFormat": "# of compute nodes used"
    },
    {
     "expr": "sum(group by(hostname) (gpu_gfx_activity{pod!=\"\", pod=\"$g_pod\"}))",
     "legendFormat": "# of compute nodes used"
    }
   ]
  },
  {
   "title": "Total Power Usage",
   "type": "stat",
   "description": "Total package power usage, in Watts",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A+$B", "type": "math" },
    { "expression": "$C+$D", "type": "math" }
   ]
  },
  {
   "title": "Total PCIe Bandwidth",
   "type": "timeseries",
   "description": "Total PCIe bandwidth over time",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum(pcie_bandwidth{job_id!=\"\", job_id=\"$g_job_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(pcie_bandwidth{pod!=\"\", pod=\"$g_pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated GPUs",
   "type": "stat",
   "description": "\\# of GPUs allocated by the job",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group by(gpu_uuid) (gpu_gfx_activity{job_id!=\"\", job_id=\"$g_job_id\"}))",
     "legendFormat": "Allocated by Jobs"
    },
    {
     "expr": "sum(group by(gpu_uuid) (gpu_gfx_activity{pod!=\"\", pod=\"$g_pod\"}))",
     "legendFormat": "Allocated by Pods"
    },
    {
     "expr": "sum(group by(gpu_id) (gpu_gfx_activity{job_id!=\"\", job_id=\"$g_job_id\"} > 0))",
     "legendFormat": "Busy GPUs"
    },
    {
     "expr": "sum(group by(gpu_id) (gpu_gfx_activity{pod!=\"\", pod=\"$g_pod\"} > 0))",
     "legendFormat": "Busy GPUs"
    }
   ]
  },
  {
   "title": "Total ECC Counts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(gpu_ecc_correct_total{job_id!=\"\", job_id=\"$g_job_id\"}[$__interval]))",
     "legendFormat": "Correctable"
    },
    {
     "expr": "sum(delta(gpu_ecc_correct_total{pod!=\"\", pod=\"$g_pod\"}[$__interval]))",
     "legendFormat": "Correctable"
    },
    {
     "expr": "sum(delta(gpu_ecc_uncorrect_total{job_id!=\"\", job_id=\"$g_job_id\"}[$__interval]))",
     "legendFormat": "Uncorrectable"
    },
    {
     "expr": "sum(delta(gpu_ecc_uncorrect_total{pod!=\"\", pod=\"$g_pod\"}[$__interval]))",
     "legendFormat": "Uncorrectable"
    }
   ]
  },
  {
   "title": "Average GPU Usage",
   "type": "timeseries",
   "description": "Average of current GFX activity",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg(gpu_gfx_activity{job_id!=\"\", job_id=\"$g_job_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(gpu_gfx_activity{pod!=\"\", pod=\"$g_pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used VRAM",
   "type": "timeseries",
   "description": "% of used VRAM across GPUs the job or pod is running on",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expression": "$A/$B", "type": "math" },
    { "expression": "$C/$D", "type": "math" }
   ]
  },
  {
   "title": "Average GPU Power",
   "type": "timeseries",
   "description": "Average GPU package power",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg(gpu_package_power{job_id!=\"\", job_id=\"$g_job_id\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(gpu_package_power{pod!=\"\", pod=\"$g_pod\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(gpu_average_package_power{job_id!=\"\", job_id=\"$g_job_id\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(gpu_average_package_power{pod!=\"\", pod=\"$g_pod\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average GPU Temperature",
   "type": "timeseries",
   "description": "Average of temperature of currently used GPUs",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(gpu_edge_temperature{job_id!=\"\", job_id=\"$g_job_id\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(gpu_edge_temperature{pod!=\"\", pod=\"$g_pod\", card_model!~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(gpu_junction_temperature{job_id!=\"\", job_id=\"$g_job_id\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(gpu_junction_temperature{pod!=\"\", pod=\"$g_pod\", card_model=~\"102-G30211-00|102-G30211-0C|102-G30211-4C|102-G30212-0C|102-G30213-00|102-G30213-0C\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Memory Temperature",
   "type": "timeseries",
   "description": "Average memory temperature of currently used GPUs",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg(gpu_memory_temperature{job_id!=\"\", job_id=\"$g_job_id\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(gpu_memory_temperature{pod!=\"\", pod=\"$g_pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Sensor Temperatures",
   "type": "timeseries",
   "description": "Averages of current temperatures across GPUs used by the job or pod, in Celsius:\n- 4 HBM temperatures\n- Edge temperature\n- Junction/hotspot temperature",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "avg(gpu_hbm_temperature{job_id!=\"\", job_id=\"$g_job_id\"})",
     "legendFormat": "HBM Temperature"
    },
    {
     "expr": "avg(gpu_edge_temperature{job_id!=\"\", job_id=\"$g_job_id\"})",
     "legendFormat": "Edge Temperature"
    },
    {
     "expr": "avg(gpu_junction_temperature{job_id!=\"\", job_id=\"$g_job_id\"})",
     "legendFormat": "Junction Temperature"
    },
    {
     "expr": "avg(gpu_hbm_temperature{pod!=\"\", pod=\"$g_pod\"})",
     "legendFormat": "HBM Temperature"
    },
    {
     "expr": "avg(gpu_edge_temperature{pod!=\"\", pod=\"$g_pod\"})",
     "legendFormat": "Edge Temperature"
    },
    {
     "expr": "avg(gpu_junction_temperature{pod!=\"\", pod=\"$g_pod\"})",
     "legendFormat": "Junction Temperature"
    }
   ]
  },
  {
   "title": "All GPUs",
   "type": "table",
   "description": "List of all GPUs used by this job. Click on the row to go to that GPU's dashboard (opens new tab).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "gpu_gfx_activity{job_id!=\"\", job_id=\"$g_job_id\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu_gfx_activity{pod!=\"\", pod=\"$g_pod\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}